#include "quantum_keycodes.h"

enum my_keycodes {
    // MACROS
    M_RGB_WHITE = SAFE_RANGE,
    M_RGB_ORANGE,
    M_RGB_YELLOW,
    M_OPEN_DISPLAY_SETTINGS,

    // EMOJIS
    UKC_EMOJI_HERZ,
    UKC_EMOJI_TRAURIG_STARK,
    UKC_EMOJI_KEINE_AHNUNG,
    UKC_EMOJI_MELDEN,
    UKC_EMOJI_CHECK_MARK,
    UKC_EMOJI_ARROW_UP,
    UKC_EMOJI_ARROW_DOWN,
    UKC_EMOJI_ARROW_RIGHT,
    UKC_EMOJI_ARROW_LEFT,
};
